using System.Text.Json;
using cs2_skins_market.Models;
using MongoDB.Driver;

namespace cs2_skins_market.Services
{
    class SkinManager : ISkinService
    {
        private readonly IMongoCollection<Skin> _collection;

        public SkinManager()
        {
            var dbClient = MongoDBconnect.Instance();
            var database = dbClient.GetDatabase("cs2_skins_market");
            _collection = database.GetCollection<Skin>("Skins");

            SeedDataIfNeeded();
        }

        public List<Skin> GetAllSkins()
        {
            return _collection.Find(skin => true).ToList();
        }

        private void SeedDataIfNeeded()
        {
                // Generated by AI
            if (_collection.CountDocuments(FilterDefinition<Skin>.Empty) == 0)
            {
                string filePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "csSkins.skins.json");
                MessageBox.Show("Buraya bakıyorum: " + filePath);

                if (File.Exists(filePath))
                {
                    string json = File.ReadAllText(filePath);


                    // Generated by AI
                    var initialData = JsonSerializer.Deserialize<List<Skin>>(json, new JsonSerializerOptions
                    {
                        PropertyNameCaseInsensitive = true
                    });

                    if (initialData != null && initialData.Count > 0)
                    {
                        _collection.InsertMany(initialData);
                    }
                }
            }
        }
    }
}
