/**************************************************************************
* Nom du fichier : DbInitializer.cs
* Auteur : Ozgun Levent
* Date de création : 06.05.2026
* Description : Initialise la base de données (seed depuis JSON).
**************************************************************************/

using System.Text.Json;
using cs2_skins_market.Core.Models;
using cs2_skins_market.Data.Interfaces;
using cs2_skins_market.Data.Repositories;

namespace cs2_skins_market.Data
{
    /// <summary>
    /// Initialise les données de base nécessaires au fonctionnement de l'application.
    /// </summary>
    public static class DbInitializer
    {
        /// <summary>
        /// Initialise la base de données si nécessaire.
        /// </summary>
        public static void Initialize()
        {
            var skinRepo = new MongoSkinRepository();

            if (skinRepo.GetCount() == 0)
            {
                Seed(skinRepo);
            }
        }

        /// <summary>
        /// Insère des données initiales dans la collection de skins.
        /// </summary>
        private static void Seed(ISkinRepository skinRepo)
        {
            // Generated by AI
            if (skinRepo.GetAllSkins().Count == 0)
            {
                string filePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "db", "csSkins.skins.json");

                if (File.Exists(filePath))
                {
                    string json = File.ReadAllText(filePath);


                    // Generated by AI
                    var initialData = JsonSerializer.Deserialize<List<Skin>>(json, new JsonSerializerOptions
                    {
                        PropertyNameCaseInsensitive = true
                    });

                    if (initialData != null && initialData.Count > 0)
                    {
                        skinRepo.InsertMany(initialData);
                    }
                }
            }
        }
    }
}