using System.Text.Json;
using cs2_skins_market.Core.Models;
using cs2_skins_market.Data.Interfaces;
using cs2_skins_market.Data.Repositories;

namespace cs2_skins_market.Data
{
    public static class DbInitializer
    {
        public static void Initialize()
        {
            var skinRepo = new MongoSkinRepository();

            if (skinRepo.GetCount() == 0)
            {
                Seed(skinRepo);
            }
        }

        private static void Seed(ISkinRepository skinRepo)
        {
            // Generated by AI
            if (skinRepo.GetAllSkins().Count == 0)
            {
                string filePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "db", "csSkins.skins.json");

                if (File.Exists(filePath))
                {
                    string json = File.ReadAllText(filePath);


                    // Generated by AI
                    var initialData = JsonSerializer.Deserialize<List<Skin>>(json, new JsonSerializerOptions
                    {
                        PropertyNameCaseInsensitive = true
                    });

                    if (initialData != null && initialData.Count > 0)
                    {
                        skinRepo.InsertMany(initialData);
                    }
                }
            }
        }
    }
}